/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.text.BadLocationException;
import javax.swing.text.DefaultHighlighter;
import javax.swing.text.Highlighter;

/**
 *
 * @author guich
 */
public class jf_buscar_reemplazar extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(jf_buscar_reemplazar.class.getName());

    /**
     * Creates new form jf_buscar_reemplazar
     */
    
    public jf_buscar_reemplazar() {
    initComponents();
    setIconImage(new ImageIcon(getClass().getResource("/iconos/iconoVentanaPrincipal.png")).getImage());
    }
   
    private InterfazMC imc;
    
    public jf_buscar_reemplazar(InterfazMC imc) {
       
        initComponents();
        this.imc = imc;
        setIconImage(new ImageIcon(getClass().getResource("/iconos/iconoVentanaPrincipal.png")).getImage());
    }
    
    
    
    public void mostrarBuscar() {
        int index = tab_pane.indexOfTab("Buscar");
        if (index != -1) {
            tab_pane.setSelectedIndex(index);
        }
    }
    
    
    public void mostrarReemplazar() {
        int index = tab_pane.indexOfTab("Reemplazar");
        if (index != -1) {
            tab_pane.setSelectedIndex(index);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tab_pane = new javax.swing.JTabbedPane();
        panel_3 = new javax.swing.JPanel();
        lbl_buscar = new javax.swing.JLabel();
        txt_buscar = new javax.swing.JTextField();
        btn_buscar = new javax.swing.JButton();
        btn_cancelar_1 = new javax.swing.JButton();
        lbl_mensaje_buscar = new javax.swing.JLabel();
        panel_4 = new javax.swing.JPanel();
        lbl_buscar_palabra = new javax.swing.JLabel();
        lbl_reemplazar = new javax.swing.JLabel();
        txt_buscar_palabra = new javax.swing.JTextField();
        txt_reemplazar = new javax.swing.JTextField();
        btn_reemplazar = new javax.swing.JButton();
        btn_cancelar_2 = new javax.swing.JButton();
        lbl_mensaje_reemplazar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Buscar y Reemplazar");
        setResizable(false);

        lbl_buscar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_buscar.setText("Buscar: ");

        txt_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_buscarActionPerformed(evt);
            }
        });

        btn_buscar.setText("Buscar");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        btn_cancelar_1.setText("Cancelar");
        btn_cancelar_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelar_1ActionPerformed(evt);
            }
        });

        lbl_mensaje_buscar.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbl_mensaje_buscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panel_3Layout = new javax.swing.GroupLayout(panel_3);
        panel_3.setLayout(panel_3Layout);
        panel_3Layout.setHorizontalGroup(
            panel_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_3Layout.createSequentialGroup()
                .addGroup(panel_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_3Layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(btn_buscar)
                        .addGap(34, 34, 34)
                        .addComponent(btn_cancelar_1))
                    .addGroup(panel_3Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(lbl_buscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl_mensaje_buscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_buscar, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE))))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        panel_3Layout.setVerticalGroup(
            panel_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_3Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(panel_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_buscar)
                    .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_mensaje_buscar)
                .addGap(19, 19, 19)
                .addGroup(panel_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_buscar)
                    .addComponent(btn_cancelar_1))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        tab_pane.addTab("Buscar", panel_3);

        lbl_buscar_palabra.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_buscar_palabra.setText("Buscar palabra:");

        lbl_reemplazar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_reemplazar.setText("Reemplazar por:");

        txt_buscar_palabra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_buscar_palabraActionPerformed(evt);
            }
        });

        txt_reemplazar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_reemplazarActionPerformed(evt);
            }
        });

        btn_reemplazar.setText("Reemplazar");
        btn_reemplazar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reemplazarActionPerformed(evt);
            }
        });

        btn_cancelar_2.setText("Cancelar");
        btn_cancelar_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelar_2ActionPerformed(evt);
            }
        });

        lbl_mensaje_reemplazar.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbl_mensaje_reemplazar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panel_4Layout = new javax.swing.GroupLayout(panel_4);
        panel_4.setLayout(panel_4Layout);
        panel_4Layout.setHorizontalGroup(
            panel_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_4Layout.createSequentialGroup()
                .addGroup(panel_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_4Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(panel_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_4Layout.createSequentialGroup()
                                .addComponent(lbl_buscar_palabra)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_buscar_palabra, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_4Layout.createSequentialGroup()
                                .addComponent(lbl_reemplazar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panel_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panel_4Layout.createSequentialGroup()
                                        .addComponent(btn_reemplazar)
                                        .addGap(41, 41, 41)
                                        .addComponent(btn_cancelar_2))
                                    .addComponent(txt_reemplazar, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(panel_4Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(lbl_mensaje_reemplazar, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        panel_4Layout.setVerticalGroup(
            panel_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_4Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(panel_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_buscar_palabra)
                    .addComponent(txt_buscar_palabra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_reemplazar)
                    .addComponent(txt_reemplazar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(lbl_mensaje_reemplazar)
                .addGap(18, 18, 18)
                .addGroup(panel_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_reemplazar)
                    .addComponent(btn_cancelar_2))
                .addGap(37, 37, 37))
        );

        tab_pane.addTab("Reemplazar", panel_4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab_pane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab_pane, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_buscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_buscarActionPerformed

    private void txt_buscar_palabraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_buscar_palabraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_buscar_palabraActionPerformed

    private void txt_reemplazarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_reemplazarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_reemplazarActionPerformed

    private void btn_cancelar_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelar_1ActionPerformed
        dispose();
    }//GEN-LAST:event_btn_cancelar_1ActionPerformed

    private void btn_cancelar_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelar_2ActionPerformed
        dispose();
    }//GEN-LAST:event_btn_cancelar_2ActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        String palabra = txt_buscar.getText().trim();
        Highlighter resaltador = imc.txta_1.getHighlighter();
        resaltador.removeAllHighlights(); 

    if (!palabra.isEmpty()) {
        String texto = imc.txta_1.getText().toLowerCase();
        String palabraBuscar = palabra.toLowerCase();
        int index = texto.indexOf(palabraBuscar);
        boolean encontrado = false;

        while (index >= 0) {
            try {
                resaltador.addHighlight(
                    index,
                    index + palabraBuscar.length(),
                    new DefaultHighlighter.DefaultHighlightPainter(Color.YELLOW)
                );
                encontrado = true;
                index = texto.indexOf(palabraBuscar, index + palabraBuscar.length());
            } catch (BadLocationException ex) {
             
            }
        }

        if (encontrado) {
            lbl_mensaje_buscar.setText("Se encontró la palabra: \"" + palabra + "\"");
        } else {
            lbl_mensaje_buscar.setText("No se encontró la palabra: \"" + palabra + "\"");
        }
    } else {
        lbl_mensaje_buscar.setText("Ingresa una palabra para buscar.");
    }
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void btn_reemplazarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reemplazarActionPerformed
        String palabraBuscar = txt_buscar_palabra.getText().trim();
        String palabraReemplazo = txt_reemplazar.getText().trim();

        if (palabraBuscar.isEmpty()) {
            lbl_mensaje_reemplazar.setText("El campo 'Buscar' está vacío.");
            return;
        }

        if (imc == null || imc.txta_1 == null) {
            lbl_mensaje_reemplazar.setText("No se pudo acceder al texto principal.");
            return;
        }

        String textoOriginal = imc.txta_1.getText();

        if (textoOriginal.contains(palabraBuscar)) {
            String textoModificado = textoOriginal.replace(palabraBuscar, palabraReemplazo);
            imc.txta_1.setText(textoModificado);
            lbl_mensaje_reemplazar.setText("Se reemplazó la palabra correctamente.");
        } else {
            lbl_mensaje_reemplazar.setText("No se encontró la palabra en el texto.");
        }
    }//GEN-LAST:event_btn_reemplazarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new jf_buscar_reemplazar().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_cancelar_1;
    private javax.swing.JButton btn_cancelar_2;
    private javax.swing.JButton btn_reemplazar;
    private javax.swing.JLabel lbl_buscar;
    private javax.swing.JLabel lbl_buscar_palabra;
    private javax.swing.JLabel lbl_mensaje_buscar;
    private javax.swing.JLabel lbl_mensaje_reemplazar;
    private javax.swing.JLabel lbl_reemplazar;
    private javax.swing.JPanel panel_3;
    private javax.swing.JPanel panel_4;
    private javax.swing.JTabbedPane tab_pane;
    private javax.swing.JTextField txt_buscar;
    private javax.swing.JTextField txt_buscar_palabra;
    private javax.swing.JTextField txt_reemplazar;
    // End of variables declaration//GEN-END:variables
}
